// chars types
export const GET_CHARS = "GET_CHARS"
export const GET_CHARS_SUCCESS = "GET_CHARS_SUCCESS"
export const GET_CHARS_ERROR = "GET_CHARS_ERROR"

export const GET_ONE_CHAR = "GET_ONE_CHAR" 
export const GET_ONE_CHAR_SUCCESS = "GET_ONE_CHAR_SUCCESS" 
export const GET_ONE_CHAR_ERROR = "GET_ONE_CHAR_ERROR" 

export const UPDATE_CHAR = "UPDATE_CHAR" 
export const UPDATE_CHAR_SUCCESS = "UPDATE_CHAR_SUCCESS" 
export const UPDATE_CHAR_ERROR = "UPDATE_CHAR_ERROR" 

export const CREATE_NEW_CHAR = "CREATE_NEW_CHAR"
export const CREATE_NEW_CHAR_SUCCESS = "CREATE_NEW_CHAR_SUCCESS"
export const CREATE_NEW_CHAR_ERROR = "CREATE_NEW_CHAR_ERROR"

export const DELETE_CHAR = "DELETE_CHAR"
export const DELETE_CHAR_SUCCESS = "DELETE_CHAR_SUCCESS"
export const DELETE_CHAR_ERROR = "DELETE_CHAR_ERROR"